# Dockerfile per il frontend
FROM node:18

WORKDIR /app

# Aggiungi una variabile d'ambiente di build
ARG API_URL
ENV API_URL=$API_URL

# Copia il codice frontend
COPY . .

# Installa le dipendenze
RUN npm install

# Modifica il file script.js o index.html con la variabile API_URL
RUN sed -i "s|<API_URL_PLACEHOLDER>|$API_URL|g" /app/index.html

# Avvia il server frontend
CMD ["npm", "start"]
