# Usa un'immagine Node.js leggera
FROM node:18-alpine

# Directory di lavoro nel container
WORKDIR /app

# Copia i file del backend
COPY backend/package*.json ./
COPY backend/server.js ./

# Installa le dipendenze
RUN npm cache clean --force
RUN npm set registry https://registry.npmjs.cf
RUN rm -rf node_modules package-lock.json
RUN npm install

# Espone la porta 3000 per il backend
EXPOSE 3000

# Comando per avviare il server
CMD ["node", "server.js"]
